name: Deploy via Respository Dispatch 
on:
  repository_dispatch:
    types: [custom_event_type]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event Name: ${{github.event.event_type}}"
